CREATE TABLE rundown (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id INT NOT NULL,
  kegiatan VARCHAR(255) NOT NULL,
  tempat VARCHAR(255) NOT NULL,
  jam TIME NOT NULL,
  pembawa_acara VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);
